# Generated by Django 4.0.4 on 2022-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanerinformation',
            name='card1_company',
            field=models.CharField(max_length=50, verbose_name='Company of Credit Card 1'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card1_credit_limit',
            field=models.IntegerField(verbose_name='Credit Card 1 Credit Limit'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card1_expiry_date',
            field=models.CharField(max_length=10, verbose_name='Credit Card 1 Expiry Date'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card1_number',
            field=models.CharField(max_length=20, verbose_name='Credit Card 1 Number'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card1_outstanding_balance',
            field=models.IntegerField(verbose_name='Credit Card 1 Outstanding Balance'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card2_company',
            field=models.CharField(max_length=50, verbose_name='Company of Credit Card 2'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card2_credit_limit',
            field=models.IntegerField(verbose_name='Credit Card 2 Credit Limit'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card2_expiry_date',
            field=models.CharField(max_length=10, verbose_name='Credit Card 2 Expiry Date'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card2_number',
            field=models.CharField(max_length=20, verbose_name='Credit Card 2 Number'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='card2_outstanding_balance',
            field=models.IntegerField(verbose_name='Credit Card 2 Outstanding Balance'),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='relative_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If yes, please state their name'),
        ),
    ]
