# Generated by Django 4.0.4 on 2022-05-29 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_loanerinformation_educational_attainment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='downpayment_percent',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)], verbose_name='Downpayment (in percent)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_term',
            field=models.IntegerField(choices=[(12, '12 Months'), (18, '18 Months'), (24, '24 Months'), (36, '36 Months'), (48, '48 Months'), (60, '60 Months')]),
        ),
    ]
