# Generated by Django 4.0.4 on 2022-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_loanerinformation_card1_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanerinformation',
            name='source_product_info',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Source of Product Information'),
        ),
    ]
