# Generated by Django 4.0.4 on 2022-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_loanerinformation_source_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_derived',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_tag',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Delinquent', 'Delinquent'), ('In Loan Default', 'In Loan Default'), ('Ongoing', 'Ongoing')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_term',
            field=models.IntegerField(choices=[(12, '12 Months'), (18, '18 Months'), (24, '24 Months'), (36, '36 Months'), (48, '48 Months'), (60, '60 Months')], verbose_name='Payment Term'),
        ),
    ]
