# Generated by Django 4.0.4 on 2022-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_bankaccount_account_number_derived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_tag',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Delinquent', 'Delinquent'), ('In Loan Default', 'In Loan Default'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=20),
        ),
    ]
