# Generated by Django 4.0.4 on 2022-05-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_loan_loan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcpayment',
            name='loan_account_no',
            field=models.ForeignKey(db_column='loan_account_no', on_delete=django.db.models.deletion.PROTECT, to='App.loanapplication'),
        ),
    ]
