# Generated by Django 4.0.4 on 2022-05-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_otcpayment_loan_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otcpayment',
            name='loan_account_no',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_account_no_hashed',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='otcpayment',
            name='loan_account_no_hashed',
            field=models.ForeignKey(db_column='loan_account_no_hashed', default=1, on_delete=django.db.models.deletion.PROTECT, to='App.loanapplication'),
            preserve_default=False,
        ),
    ]
