# Generated by Django 4.0.4 on 2022-06-02 15:31

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_loanapplication_loan_account_no_hashed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='next_pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number_derived',
            field=models.CharField(blank=True, default=App.models.BankAccount.create_unique_number, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('For Review', 'For Review')], default='For Review', max_length=15),
        ),
    ]
