# Generated by Django 4.0.4 on 2022-06-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_loan_last_pay_date'),
        ('App', '0015_loan_last_pay_date_alter_loan_selling_prize'),
    ]

    operations = [
    ]
