# Generated by Django 4.0.4 on 2022-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_merge_20220603_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanerinformation',
            name='borrower_monthly_expenses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Borrower's Gross Monthly Expenses"),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='spouse_monthly_expenses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Spouse's Gross Monthly Expenses"),
        ),
    ]
