# Generated by Django 4.0.4 on 2022-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_merge_20220603_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanerinformation',
            name='spouse_monthly_expenses',
            field=models.IntegerField(blank=True, null=True, verbose_name="Spouse's Gross Monthly Expenses"),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='spouse_monthly_income',
            field=models.IntegerField(blank=True, null=True, verbose_name="Spouse's Gross Monthly Income"),
        ),
    ]
