# Generated by Django 4.0.4 on 2022-06-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_loanerinformation_borrower_monthly_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanerinformation',
            name='tin',
            field=models.CharField(max_length=15, verbose_name='Tax Identification Number (TIN)'),
        ),
    ]
