# Generated by Django 4.0.4 on 2022-06-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_loanerinformation_spouse_monthly_expenses_and_more'),
        ('App', '0018_alter_loanerinformation_tin'),
    ]

    operations = [
    ]
