# Generated by Django 4.0.4 on 2022-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_merge_20220603_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='borrower_monthly_expenses',
            field=models.IntegerField(verbose_name="Borrower's Gross Monthly Expenses"),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='spouse_monthly_expenses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Spouse's Gross Monthly Expenses"),
        ),
        migrations.AlterField(
            model_name='loanerinformation',
            name='spouse_monthly_income',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Spouse's Gross Monthly Income"),
        ),
    ]
